spring.application.name=kiyim_online_dokon

# PostgreSQL bilan ishlash uchun
spring.datasource.url=jdbc:postgresql://localhost:5432/kiyim_online_dokon
spring.datasource.username=postgres
spring.datasource.password=1308
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate sozlamalari
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true




